require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/group_entities", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # GroupEntity. As you add validations to GroupEntity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GroupEntity.create! valid_attributes
      get group_entities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      group_entity = GroupEntity.create! valid_attributes
      get group_entity_url(group_entity)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_group_entity_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      group_entity = GroupEntity.create! valid_attributes
      get edit_group_entity_url(group_entity)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GroupEntity" do
        expect {
          post group_entities_url, params: { group_entity: valid_attributes }
        }.to change(GroupEntity, :count).by(1)
      end

      it "redirects to the created group_entity" do
        post group_entities_url, params: { group_entity: valid_attributes }
        expect(response).to redirect_to(group_entity_url(GroupEntity.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GroupEntity" do
        expect {
          post group_entities_url, params: { group_entity: invalid_attributes }
        }.to change(GroupEntity, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post group_entities_url, params: { group_entity: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested group_entity" do
        group_entity = GroupEntity.create! valid_attributes
        patch group_entity_url(group_entity), params: { group_entity: new_attributes }
        group_entity.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the group_entity" do
        group_entity = GroupEntity.create! valid_attributes
        patch group_entity_url(group_entity), params: { group_entity: new_attributes }
        group_entity.reload
        expect(response).to redirect_to(group_entity_url(group_entity))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        group_entity = GroupEntity.create! valid_attributes
        patch group_entity_url(group_entity), params: { group_entity: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested group_entity" do
      group_entity = GroupEntity.create! valid_attributes
      expect {
        delete group_entity_url(group_entity)
      }.to change(GroupEntity, :count).by(-1)
    end

    it "redirects to the group_entities list" do
      group_entity = GroupEntity.create! valid_attributes
      delete group_entity_url(group_entity)
      expect(response).to redirect_to(group_entities_url)
    end
  end
end
